import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //write code here
        SalesPromotion salesPromotion = salesPromotionRepository.findAll().get(1);
        List<String> relatedItems = salesPromotion.getRelatedItems();
        List<Item> items = itemRepository.findAll();
        int priceA=halfPrice(inputs,relatedItems);
        int priceB=fullReduction(inputs);
        int normal = normalPrice(inputs);
        String a;
        if(normal >= 30 && priceA >= priceB){
            a="============= Order details =============\n" +
                    toStringInput(inputs)+
                    "-----------------------------------\n" +
                    "Promotion used:\n" +
                    "满30减6 yuan，saving "+ (normal-priceB)+" yuan\n" +
                    "-----------------------------------\n" +
                    "Total:"+priceB+" yuan\n" +
                    "===================================";
        } else if(priceA<priceB){
            a="============= Order details =============\n" +
                    toStringInput(inputs)+
                    "-----------------------------------\n" +
                    "Promotion used:\n" +
                    "Half price for certain dishes (Braised chicken，Cold noodles)，saving "+(normalPrice(inputs)-halfPrice(inputs,relatedItems))+" yuan\n" +
                    "-----------------------------------\n" +
                    "Total:"+halfPrice(inputs,relatedItems)+" yuan\n" +
                    "===================================";
        }else{
            a="============= Order details =============\n" +
                    toStringInput(inputs)+
                    "-----------------------------------\n" +
                    "Total:"+normalPrice(inputs)+" yuan\n" +
                    "===================================";
        }

        System.out.println(a);
        return a;
    }
    public int halfPrice(List<String> inputs,List<String> relatedItems){
        int totalPrice=0;
        for (String commodity : inputs) {
            commodity = commodity.replace(" ","");
            String commodityId = commodity.split("x")[0];
            String commodityCount = commodity.split("x")[1];
            Item item=getItemById(commodityId,itemRepository.findAll());
            if (relatedItems.contains(commodityId)) {
                totalPrice+=item.getPrice()/2*Double.parseDouble(commodityCount);
            }else{
                totalPrice+=item.getPrice()*Double.parseDouble(commodityCount);
            }
        }
        return totalPrice;
    }
    public int fullReduction(List<String> inputs){
        int totalPrice=0;
        for (String commodity : inputs) {
            commodity = commodity.replace(" ","");
            String commodityId = commodity.split("x")[0];
            String commodityCount = commodity.split("x")[1];
            Item item=getItemById(commodityId,itemRepository.findAll());
            totalPrice+=item.getPrice()*Integer.parseInt(commodityCount);
        }
        totalPrice=totalPrice-(totalPrice/30)*6;
        return totalPrice;
    }
    public Item getItemById(String id,List<Item> items){
        for (Item item : items) {
            if (item.getId().equals(id)) {
                return item;
            }
        }
        return null;
    }
    public String toStringInput(List<String> inputs){
        String input="";
        for (String commodity : inputs) {
            commodity = commodity.replace(" ","");
            String commodityId = commodity.split("x")[0];
            String commodityCount = commodity.split("x")[1];
            Item item=getItemById(commodityId,itemRepository.findAll());
            input+=item.getName()+" x "+commodityCount+" = "+(int)(item.getPrice()*Integer.parseInt(commodityCount))+" yuan\n";
        }
        return input;
    }
    public int normalPrice(List<String> inputs){
        int totalPrice=0;
        for (String commodity : inputs) {
            commodity = commodity.replace(" ","");
            String commodityId = commodity.split("x")[0];
            String commodityCount = commodity.split("x")[1];
            Item item=getItemById(commodityId,itemRepository.findAll());
            totalPrice+=item.getPrice()*Double.parseDouble(commodityCount);
        }
        return totalPrice;
    }



}
